name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: charifray/bonjour21:${{ github.run_number }}
  DOCKER_REGISTRY: docker.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout le code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Java & Maven
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
        cache: maven

    # 3. Test le projet Maven
    - name: Run Maven tests
      run: mvn clean test

    # 4. Build le projet Maven
    - name: Build Maven project
      run: mvn clean package -DskipTests

    # 5. Login Docker Hub
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 6. Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_IMAGE }} .

    # 7. Push Docker image
    - name: Push Docker image
      run: docker push ${{ env.DOCKER_IMAGE }}

    # 8. Setup kubectl
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # 9. Setup KUBECONFIG
    - name: Set up KUBECONFIG
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    # 10. Deploy to Kubernetes
    - name: Apply Kubernetes manifests
      run: |
        echo "DÃ©ploiement en cours via kubectl..."
        kubectl apply -f bonjour.yaml
