name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: charifray/bonjour21:${{ github.run_number }}
  DOCKER_REGISTRY: docker.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout le code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Java & Maven
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Maven
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
        cache: maven

    # 3. Build le projet Maven
    - name: Build Maven project
      run: mvn clean package -DskipTests

    # 4. Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 5. Build Docker image
    - name: Build Docker image
      run: docker build -t $DOCKER_IMAGE .

    # 6. Push Docker image
    - name: Push Docker image
      run: docker push $DOCKER_IMAGE

    # 7. Deploy (kubectl)
   # - name: Deploy to Kubernetes
    #  uses: azure/setup-kubectl@v3
    #  with:
   #     version: 'latest'
   #   env:
    #    KUBECONFIG: ${{ secrets.KUBECONFIG }}
     # run: |
     #   echo "Déploiement possible via kubectl..."
     #   # Exemple réel:
        # kubectl apply -f k8s/deployment.yaml
